name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Submodules'ü yüklemek için bu satırı ekleyin
        fetch-depth: 0     # Full history'i çekmek için

    - name: Install Zola
      run: |
        wget https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz
        tar xvzf zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz
        sudo mv zola /usr/local/bin

    - name: Build the site
      run: zola build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
